### ISSUE TITLE
Name generator prompts override field value instead of adding one (categorical field)

### ISSUE THREAD

**Issue by lleleux** [complexdatacollective/Interviewer#1051]
Hi,

I have a name generator, with 4 prompts. Each prompt has a side panel that use the network from the in-progress interview, and assign one value to the categorical field. There are 4 values for this categorical field, each one has his prompt.
So, if I create an alter in the first prompt, the field will have the first value, if I drag and drop it from the panel into the second prompt, I would like to assign the second value to the field. But NC override the field value with only the 2e value, instead of adding it. So I loose the first value.

This is a bug ? Or is there another manner to add values to a categorical field without loosing the old values ?

Thank you for your answer.

Laurent

**Comment by jthrilly** [comment]
Hi Laurent - thanks so much for this report.

I can understand why this is confusing! In my opinion this is functioning correctly, but I can definitely see it both ways.

Let me talk about this issue with the rest of the team, and get back to you.

In the meantime, I am sure you are aware that you can model the same data using multiple boolean variables instead. Because of the way categorical variables are exported, the data will even look very similar when you analyze it if you do this. Hopefully this helps.

**Comment by lleleux** [comment]
Hi,

Thank you for your answer.
Sure, I can use multiple boolean variables, but if I do that, I cannot use the great categorical input for the same field later. In my protocol, I have the name generator, and later, I have an alter form to add info per alter, and possibly update the field with the categorical input. I can add 4 questions for the 4 booleans, but it's not as easy than the categorical input.

**Comment by jthrilly** [comment]
I suppose on a philosophical level, one issue with making this work as you describe is how to handle removing a value from a categorical variable. With your approach, it would only be possible to add additional categorical membership.

This is not an issue with boolean or even text/numerical variables - the value can simply be set to something falsey.

One option would be to add a third state to the interface where you set the value for the categorical variable on the prompt:

<img width="276" alt="Screen Shot 2020-05-28 at 8 43 38 PM" src="https://user-images.githubusercontent.com/1387940/83186126-f08e3400-a123-11ea-9a7f-f0f23d0e94e7.png">

The intermediate state could imply "whatever existing value is present", and then checked and unchecked can be used to set and remove. However this is fairly complex to implement, and would require a schema change. We probably won't have time to get this done before the stable release at the end of June.

In the short term, we will modify the behaviour of categorical variables used as additional attributes on prompts to be additive.

**Comment by lleleux** [comment]
You are right, the option you describe here will solve the problem, and handle both cases !
Thank you for your answer.

**Comment by lleleux** [comment]
Hi,

Any update about this? Do you know when this issue will be handled?

Thank you,

Laurent

**Comment by jthrilly** [comment]
Hi @lleleux - I'm afraid not. We are all focusing on major bug fixes and features for the stable release, which will be very soon. I promise to look at the issue again before then.

**Comment by jthrilly** [comment]
@lleleux - we looked into the issue and im afraid to say it unearthed some flawed assumptions regarding the feature itself We are going to be evaluating what to do next in the coming weeks, but for now I would suggest you and any others impacted by this to use a series of boolean variables, rather than a categorical variable, for this kind of task.
