### ISSUE TITLE
No 6.0 version for Linux ?

### ISSUE THREAD

**Issue by lleleux** [complexdatacollective/Interviewer#1108]
How can I update on Linux ? I didn't see any update on snapcraft.
On the website, the download button for Linux links to the github release, and there is only a .exe and .dmg, nothing for Linux.

Thanks in advance for your answer.

Laurent

**Comment by wwqrd** [comment]
Hi @lleleux,

I've added .deb and .snap builds to the release (https://github.com/complexdatacollective/Interviewer/releases/tag/v6.0.0).

We've been primarily focused on the .deb build here, which is fully functional. The .snap build does not support automatic server discovery at the moment.

To install the snap from a local package you will need to use the `--dangerous` flag. Once the snap is published on Snapcraft you should be able to install it normally, but that may be a few days since some of the team are away for Christmas.

I haven't posted builds for the other apps yet, but plan to do that later today.

**Comment by wwqrd** [comment]
I've now added the other builds as .deb packages. Having issues with .snap packages at the moment:
- Server https://github.com/complexdatacollective/Server/releases/tag/v6.0.0
- Architect https://github.com/complexdatacollective/Architect/releases/tag/v6.0.0

**Comment by lleleux** [comment]
Thank you !

It's OK for me with the .deb versions.
