### ISSUE TITLE
dyad sociogram discrepancy

### ISSUE THREAD

**Issue by rebeccamadsen** [complexdatacollective/Interviewer#1157]
Creating a link on sociogram only shows up on the dyad census if the link was created in the same direction as the dyad census asks. For example, if a user creates a link between Joseph and Henry on the sociogram, but the Dyad asks about Henry and Joseph, then the Dyad will show a non-answer.

Related, if you have that link existing in sociogram but mark "no" in the Dyad Census, you would expect the link to disappear in the Sociogram, but it does not. Directionality appears to matter. Is this intentional?

Possibly a minor issue if users don't typically use both Dyad and Sociogram.

**Comment by jthrilly** [comment]
This is a great catch @rebeccamadsen!

In theory, both interfaces should be extendable to _support_ directed edges, but neither should be enforcing that right now. This is definitely a bug, but as you say, people will not generally use both interfaces (though that will change with the introduction of the automatic layout feature).

I think the fix for this has to be to update the dyad census edge selector for the pair to account for edge existing in either direction.
